baseURL: https://ideas.paultraylor.dev
languageCode: en-us
title: Assorted Ideas
theme:
  - worklog
  - bootstrap4
SectionPagesMenu: main
enableGitInfo: true
rssLimit: 10
params:
  description: "Assorted ideas and brainstorming"
  twitter: "https://twitter.com/kfdm"
  github: "https://github.com/kfdm"
  # recent_posts_number: 5
  show_reading_time: true

taxonomies:
  category: categories
  tag: tags
  status: status

permalinks:
  worklog: /worklog/:year/:month/:day/
